version: '3.3'
services:
  db:
    container_name: mysql
    image: mysqldb
    build: ./databases
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - '3306:3306'
    expose:
      - '3306'
