version: '3.3'
services:
  db:
    container_name: mysql
    image: mysqldb
    build: ./databases
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=pb
    ports:
      - '3306:3306'
    expose:
      - '3306'

  redis:
    hostname: redis
    image: redis:alpine
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"

