swagger: "2.0"
info:
  version: 1.0.0
  title: catalog-system
  description: My cool app
basePath: /api/v1
tags:
  - name: Collections
    description: Collection endpoints

consumes:
  - application/json
produces:
  - application/json


definitions:
  CollectionBody:
    type: object
    title: collections
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /collections:
    get:
      tags:
        - Collections
      description: Fetch all collection
      responses:
        200:
          description: Returns all collection
    post:
      tags:
        - Collections
      description: Create a new collection
      parameters:
        - name: collection
          in: body
          description: an collection
          required: true
          schema:
            $ref: "#/definitions/CollectionBody"
      responses:
        200:
          description: Returns all collection

  /collections/{id}:
    get:
      tags:
        - Collections
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the collection to retrieve
          type: integer
      responses:
        200:
          description: Return the collection with the specified id
        404:
          description: Collection not found

